import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeroProvider from "@/providers/hero-provider";
import SessionProvider from "@/providers/session-provider";
import Header from "@/components/header";
import TrpcProvider from "@/providers/trpc-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  intercepting,
}: Readonly<{
  children: React.ReactNode;
  intercepting: React.ReactNode;
}>) {
  return (
    <html lang="en" className='dark'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <TrpcProvider>
            <HeroProvider>
              <Header />
              <div className="max-w-[1024px] p-6 mx-auto">
                {children}
              </div>
              {intercepting}
            </HeroProvider>
          </TrpcProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
